export const EDITORIAL_GUIDES = [
  {
    slug: "how-to-write-a-formal-petition-in-nigeria",
    category: "Petition writing",
    title: "How to write a clear formal petition in Nigeria",
    description: "A practical guide to stating facts, identifying the correct respondent, requesting a realistic remedy and submitting a formal complaint in Nigeria.",
    audience: "Anyone preparing a complaint to a business, public institution, regulator or other responsible organisation.",
    context: [
      "A useful petition is a structured request for an institution to examine a problem and provide a practical response. It is not improved by threats, dramatic language or copying every public authority that comes to mind. The strongest starting point is a short, verifiable account of what happened, who was involved, when it happened and the specific outcome being requested.",
      "Identify the organisation that actually made the decision, delivered the service, managed the transaction or controls the records needed to resolve the problem. An employer, bank, payment processor or agency mentioned in the background is not automatically the proper respondent. Distinguish the decision-maker from a witness, documentary source or institution that merely provided supporting evidence.",
      "Set out the facts in chronological order. Separate what you personally observed from what you suspect or infer. Use exact dates and references where available, preserve the original amount of any disputed transaction, and explain what you did to seek a resolution. If information is missing, acknowledge that it is unavailable instead of filling the gap with an assumption.",
      "A good request is concrete enough to answer. You might ask for an investigation, a written explanation, correction of a record, release of a withheld document, reversal of a disputed charge, or confirmation of the applicable review procedure. Ask for compensation only where you can explain the loss or hardship and avoid describing it as an entitlement before the facts have been examined.",
    ],
    checklist: ["Your full name and a contact method you actively use", "The responsible organisation and relevant department", "A dated sequence of the material events", "Accurate transaction, application or complaint references", "Copies of supporting records with unnecessary personal data removed", "A clear remedy and a request for a written response"],
    route: "Start with the organisation responsible for the underlying decision unless an urgent safety concern, a legally mandated filing route or an existing unresolved complaint makes another route appropriate. Use a verified official email address, recognised portal, physical registry or another published channel and retain proof of delivery.",
    escalation: "Escalation should follow the actual subject matter and the steps already taken. Record the original complaint reference, submission date, any response and the outstanding issue. A regulator, ombudsman, disciplinary body or court will require different information; copying unrelated institutions does not strengthen the case.",
    example: "A customer disputing a deduction should state the date, exact amount, recognised repayment obligation, disputed mandate and requested reconciliation. If a bank statement only proves that no loan was received, the statement is evidence; the lender or payment processor remains the relevant respondent.",
    mistake: "Avoid unsupported criminal accusations, copied legal quotations, invented deadlines, guessed email addresses and demands that an organisation cannot lawfully satisfy. Do not publish another person's identity documents, account credentials, passwords, PINs or one-time codes.",
    sources: [{label:"Public Complaints Commission",url:"https://pcc.gov.ng/"},{label:"SERVICOM",url:"https://servicom.gov.ng/"}],
    faqs: [{question:"Does a petition have to be written by a lawyer?",answer:"A person can prepare a factual administrative complaint, but legal representation may be appropriate where the matter involves litigation, urgent rights protection, complex contracts or significant financial exposure."},{question:"Should I send a complaint to every regulator?",answer:"No. Address the responsible organisation first and involve only an oversight body that has a genuine connection to the issue and the current complaint stage."}],
  },
  {
    slug: "banking-and-financial-complaints",
    category: "Banking and financial services",
    title: "Banking complaints: disputed debits, loans, transfers and repayment mandates",
    description: "Work out whether a bank, digital lender or payment processor is responsible, preserve transaction evidence and escalate an unresolved Nigerian financial complaint safely.",
    audience: "Customers dealing with failed transfers, unexplained debits, digital loans, payroll deductions, wallet transactions or account restrictions.",
    context: [
      "Financial complaints often involve more than one company. A customer may borrow from a digital lender, receive salary through a payroll platform and use a separate bank account to view the resulting statement. The name on the account statement does not automatically identify the lender that originated a disputed obligation or the processor that applied a repayment mandate.",
      "Map the transaction before choosing a recipient. Identify who offered or serviced the loan, who received the disputed money, who created or processed the mandate, and which institution simply holds the account used as evidence. The provider responsible for the challenged product or deduction should usually receive the first complaint, while a directly involved payment processor may also need a copy.",
      "For a disputed loan deduction, compare the application, repayment schedule, actual disbursement, deduction date and every mandate reference. If you authorised one instalment but an additional amount was deducted for a loan you say was never disbursed, describe the legitimate facility separately from the challenged debit. Do not present all repayments as fraudulent when only one transaction is disputed.",
      "PetitionDesk distinguishes ordinary banking complaints from loan, credit and excess-charge complaints when assessing whether provider follow-up or regulator escalation is appropriate. Preserve the provider's complaint reference and complaint date; without both, it may be impossible to establish that a regulator-stage complaint is ready.",
    ],
    checklist: ["The name of the lender, bank, wallet operator or processor complained against", "The disputed amount, transaction date and account or repayment reference", "Any loan agreement, disbursement evidence and genuine repayment schedule", "Mandate references and proof of the disputed deduction", "A relevant account statement with sensitive information redacted", "Earlier complaint correspondence, reference and submission date"],
    route: "Complain first to the institution responsible for the disputed financial product or transaction. Where a payroll lender and a named mandate processor are directly involved, address the lender and copy the processor through verified channels. Do not address an account-statement bank unless your complaint concerns that bank's own conduct.",
    escalation: "If the provider does not resolve the complaint, organise the original complaint date, reference, response and supporting evidence before approaching the relevant financial regulator. Ask the authority to determine the applicable rule rather than inventing a regulatory deadline, mandatory penalty or fixed compensation entitlement.",
    example: "If VeendHQ provided a Remita payroll loan and an additional deduction appears under a Remita mandate, the lender is the primary respondent and Remita may be a relevant copied participant. A FirstBank statement showing that no matching loan disbursement was received is supporting evidence, not proof that FirstBank provided the loan.",
    mistake: "Do not combine a genuine loan with a disputed separate deduction, omit the mandate reference, expose a complete account number publicly or assume a payment platform and a deposit-taking bank have identical responsibilities.",
    sources: [{label:"Central Bank of Nigeria complaints portal",url:"https://complaintsportal.cbn.gov.ng/"},{label:"VeendHQ Remita payroll loan information",url:"https://veendhq.com/products/remita-payroll-loan"},{label:"Remita official support portal",url:"https://support.remita.net/portal/en/home"}],
    faqs: [{question:"Should the account-statement bank always receive the petition?",answer:"No. The account-statement provider is the correct respondent only where the complaint challenges that bank's own action, omission, account restriction or processing role."},{question:"What if there is no evidence that the disputed loan was disbursed?",answer:"Say that the supplied records do not show the alleged disbursement and request the lender's application, customer authorisation, mandate and disbursement evidence."}],
  },
  {
    slug: "electricity-billing-and-meter-complaints",
    category: "Power and electricity",
    title: "Electricity complaints: estimated bills, meters, disconnections and supply",
    description: "Prepare a useful complaint about an electricity distribution company, disputed meter reading, estimated bill, disconnection or supply problem in Nigeria.",
    audience: "Residential or business electricity customers challenging a bill, connection decision, meter issue or unresolved service interruption.",
    context: [
      "A power complaint becomes easier to investigate when it identifies the electricity distribution company, the service address and the relevant billing period. A general statement that electricity supply is poor rarely shows whether the problem concerns a disputed bill, a damaged meter, a service connection, a prolonged outage or a disconnection decision.",
      "For billing disputes, compare the account number, customer classification, recorded meter reading, amount demanded and previous bills. If the meter stopped working or the bill was estimated, explain the date the problem was reported and preserve any technician visit record. Do not assume every high bill is unlawful; identify the specific charge or reading you want reviewed.",
      "Where the complaint involves disconnection, describe the notice received, the date service stopped, any disputed arrears and the effect on the household or business. Separate an emergency safety issue, such as exposed wiring or a damaged transformer, from an ordinary billing disagreement and report an immediate hazard through the relevant emergency channel first.",
      "Electricity oversight may depend on the distribution area and whether responsibility sits with the national regulator, a recognised consumer forum or a state electricity authority. The location supplied in the complaint therefore matters as much as the provider name.",
    ],
    checklist: ["Distribution company and electricity account or meter number", "Service address and state", "Disputed bills, receipts and meter readings", "Dates of outages, visits or disconnection", "The provider complaint reference and response", "Photographs or maintenance records where safely available"],
    route: "Start with the electricity distribution company serving the affected address. Use its official customer-care or complaint channel, request a reference and identify the billing or connection decision being challenged. An existing unresolved provider complaint may support referral to the applicable electricity consumer forum or regulator.",
    escalation: "When the provider does not resolve the matter, submit the earlier complaint, service address, account details, disputed bills and the remedy requested to the authority with jurisdiction over that electricity market. Confirm whether a national forum or state-level regulator is responsible before sending the petition.",
    example: "A customer in Abuja disputing several months of estimated charges should identify the distribution company, attach the affected bills, state whether a functioning meter exists and request a documented meter inspection, billing reconciliation and written outcome.",
    mistake: "Do not quote a tariff, reconnection fee, compensation amount or statutory timeline unless it comes from a verified current source that applies to the customer category and location.",
    sources: [{label:"Nigerian Electricity Regulatory Commission",url:"https://nerc.gov.ng/"},{label:"NERC Abuja consumer forum",url:"https://nerc.gov.ng/forum-offices/abuja-forum-office/"}],
    faqs: [{question:"Can I bypass the electricity company immediately?",answer:"Usually begin with the provider unless there is an immediate danger, a documented unresolved complaint or another established route requiring direct contact with the regulator."},{question:"Does my location matter?",answer:"Yes. The service address helps determine the distribution company, the correct forum and whether a relevant state electricity authority has jurisdiction."}],
  },
  {
    slug: "telecom-airtime-data-and-network-complaints",
    category: "Telecommunications",
    title: "Telecom complaints about airtime, data, subscriptions and network service",
    description: "Document airtime deductions, failed data bundles, unwanted subscriptions and unresolved telecom service problems before approaching the correct Nigerian provider or regulator.",
    audience: "Mobile and internet subscribers dealing with unexplained charges, poor connectivity, subscription problems or unresolved account restrictions.",
    context: [
      "A telecommunications complaint should identify the network operator, the affected service and the particular transaction or service interruption. Lost airtime, an unwanted recurring subscription, a failed data bundle and prolonged coverage problems involve different records and may need different internal teams.",
      "Start by recording the affected phone number in a privacy-conscious format, the date and amount charged, any recharge or transaction reference and the service you expected to receive. Where an unwanted subscription is involved, state when you noticed it, whether you attempted to unsubscribe and what the operator or content provider communicated.",
      "Network quality complaints should describe the location, dates, type of interruption and steps already taken. An isolated temporary outage is not the same as a repeated service failure affecting an area over several weeks. Screenshots, support chats and reference numbers help establish the pattern without relying on exaggerated claims.",
      "Provider-first routing is especially important because the network operator controls account history, billing records and technical fault information. A regulator-stage complaint becomes stronger when it includes the operator's ticket number and a clear explanation of why the response was inadequate.",
    ],
    checklist: ["Network operator or internet-service provider", "Affected line or account with unnecessary digits masked", "Airtime, data or subscription amount and date", "Support ticket, recharge reference or transaction receipt", "Location and duration of any network problem", "Screenshots and copies of prior operator communications"],
    route: "Submit the initial complaint through the operator's official support, customer-care, app or complaint channel and request a ticket reference. Explain whether the desired result is a refund, cancellation, service restoration, billing explanation or correction of account records.",
    escalation: "If the operator does not resolve the issue, provide the earlier ticket reference, complaint date, account details and response when using the Nigerian Communications Commission's published consumer-complaint process. Do not assume a regulator can investigate a matter that has no identifiable provider or support history.",
    example: "If a data bundle was debited but never delivered, state the purchase date, bundle price, payment reference, account balance before and after, the operator's complaint reference and your request for delivery or refund.",
    mistake: "Avoid sharing SIM-registration documents, full identity numbers, account passwords, one-time codes or unrelated private conversations when a masked transaction screenshot would be sufficient.",
    sources: [{label:"NCC consumer complaint form",url:"https://consumer.ncc.gov.ng/consumer-complaints/complaint-form"},{label:"MTN Nigeria official support",url:"https://www.mtn.ng/contact/"}],
    faqs: [{question:"Should I keep the network provider's complaint ticket?",answer:"Yes. A support ticket or complaint reference helps the operator locate your case and supports a later regulator complaint if the issue remains unresolved."},{question:"Can I complain about an unwanted subscription?",answer:"Yes. Identify the date, amount, subscription label, relevant messages and any attempt to cancel so the operator can trace the billing event."}],
  },
  {
    slug: "flight-delay-cancellation-and-refund-complaints",
    category: "Aviation",
    title: "Airline complaints: cancelled flights, delay, baggage and unpaid refunds",
    description: "Document a Nigerian flight disruption, request a realistic remedy from the airline and identify when a civil-aviation regulator complaint is appropriate.",
    audience: "Passengers affected by a cancelled or delayed flight, missing baggage, denied boarding or an unresolved ticket refund.",
    context: [
      "The airline that issued or operated a ticket is generally the first organisation that can confirm what happened to a booking. A useful complaint identifies the carrier, booking reference, route, scheduled departure, actual event and the remedy requested. A travel agent or payment platform may also matter if it received the ticket money or handled a refund request.",
      "Distinguish a delayed departure from a complete cancellation, a missed connection, denied boarding or a baggage problem. Preserve the boarding pass, booking confirmation, receipts and any message informing passengers of the change. If you paid for alternative transport or accommodation, explain the actual expense without assuming it must automatically be reimbursed.",
      "Refund disputes should state the original amount, payment method, date the refund was requested and the response received. If the airline says a refund was processed, ask for the payment reference and the channel to which the money was sent. Avoid calling an unresolved refund theft without evidence establishing that conclusion.",
      "A safety incident requires different treatment from an ordinary customer-service disagreement. Report immediate danger through the appropriate emergency or aviation-safety channel and preserve factual observations without compromising your own safety or an active investigation.",
    ],
    checklist: ["Airline name, booking reference and flight number", "Original route, scheduled departure and actual disruption", "Ticket receipt, boarding pass and carrier communications", "Refund request date, amount and any payment reference", "Reasonable documented expenses resulting from the disruption", "Existing airline complaint reference and written response"],
    route: "Complain first to the relevant airline or authorised ticketing organisation using its official support channel. Ask for a case reference and identify whether you want rebooking, information, baggage tracing, refund verification or another appropriate remedy.",
    escalation: "An unresolved airline consumer complaint may be directed to the Nigerian Civil Aviation Authority using the published consumer-protection process. Supply the airline complaint history, ticket details and supporting records. Refer a genuine safety concern to the authority responsible for aviation safety rather than treating it as a routine refund dispute.",
    example: "A passenger whose Lagos–Abuja flight was cancelled should list the flight date, booking reference, amount paid, alternative arrangement offered, date of the refund request and the exact written response received from the airline.",
    mistake: "Do not state a fixed compensation entitlement, statutory percentage or deadline unless you have checked the current rule applicable to the particular flight, carrier and circumstances.",
    sources: [{label:"NCAA Consumer Protection Directorate",url:"https://cpd.ncaa.gov.ng/"},{label:"Nigerian Safety Investigation Bureau",url:"https://nsib.gov.ng/"}],
    faqs: [{question:"Is every delayed flight automatically a compensation claim?",answer:"No. Available remedies depend on the applicable rules, the reason for the disruption, the booking conditions and the evidence supplied."},{question:"What if the airline says it already refunded me?",answer:"Request the refund date, transaction reference, amount and destination payment channel, then compare those details with your bank or payment records."}],
  },
  {
    slug: "hospital-hmo-and-health-insurance-complaints",
    category: "Health and public health insurance",
    title: "Hospital, HMO and public health-insurance complaints",
    description: "Identify whether a hospital, health-maintenance organisation, insurer or health regulator is responsible for a treatment, referral, authorisation or billing complaint.",
    audience: "Patients and families dealing with treatment delays, referral authorisation problems, medical billing, professional conduct or health-plan coverage.",
    context: [
      "Health-service complaints can involve a hospital, an individual practitioner, a health-maintenance organisation and a public or private insurance scheme. Identify which party controlled the disputed decision. A delayed treatment authorisation may sit with an HMO, while an unsafe clinical practice or refusal to provide treatment records may require a different route.",
      "Begin with a factual timeline showing when care was requested, what treatment or referral was involved, what authorisation was sought and what response followed. Explain the impact on the patient without claiming that negligence occurred unless qualified evidence supports that allegation. Medical records should be shared only where necessary and with appropriate authority.",
      "For insurance authorisation problems, identify the enrollee or plan reference, provider facility, requested service, date of submission and the reason given for refusal or delay. Ask the responsible HMO or scheme administrator to explain the applicable coverage decision and provide a documented resolution.",
      "Where urgent medical treatment is needed, obtain appropriate clinical or emergency assistance first. A complaint document should never delay life-saving care, expose a patient's confidential diagnosis unnecessarily or substitute for a professional medical assessment.",
    ],
    checklist: ["Name of the hospital, practitioner, HMO or health plan", "Relevant treatment, referral or authorisation dates", "Plan or enrolment reference with sensitive identifiers protected", "Bills, written decisions and provider correspondence", "Factual description of the effect on treatment access", "Any prior complaint reference or escalation response"],
    route: "Contact the party responsible for the disputed decision: the hospital for a provider-service problem, the HMO for an authorisation or coverage decision, or the relevant professional body for practitioner conduct where appropriate. Preserve confidentiality and ask for a complaint reference.",
    escalation: "An unresolved public health-insurance issue may require the relevant scheme or health-insurance authority, while clinical discipline and product safety may belong to separate professional or regulatory institutions. Select the route according to the actual complaint rather than sending confidential medical information to unrelated bodies.",
    example: "If an HMO failed to authorise a specialist referral, record the referral date, requesting hospital, enrollee reference, authorisation request, response received and the practical impact of the delay, then ask for a prompt written coverage decision.",
    mistake: "Do not upload complete medical histories, diagnosis details or another patient's records when a limited treatment timeline and the relevant authorisation correspondence will establish the issue.",
    sources: [{label:"National Health Insurance Authority",url:"https://www.nhia.gov.ng/"},{label:"National Human Rights Commission",url:"https://www.nigeriarights.gov.ng/"}],
    faqs: [{question:"Should a hospital and an HMO receive the same complaint?",answer:"Only when both played a direct role. Identify the organisation that made the contested decision and include another provider only where its records or conduct are genuinely relevant."},{question:"What if medical attention is urgent?",answer:"Seek emergency medical assistance immediately. The complaint process is a later administrative step and must not delay necessary care."}],
  },
  {
    slug: "insurance-policy-and-claim-complaints",
    category: "Insurance",
    title: "Insurance complaints about rejected claims, delays and policy disputes",
    description: "Understand what to include when an insurer delays a decision, rejects a claim or disputes cover, and how to prepare an evidence-based complaint.",
    audience: "Policyholders and beneficiaries experiencing an unresolved motor, property, life, business or other insurance claim dispute.",
    context: [
      "An insurance complaint should distinguish the policyholder's expectations from the actual policy terms and the insurer's stated reasons. Identify the insurer, policy type, policy number, event giving rise to the claim and the documents already submitted. A delayed decision, refusal to acknowledge a claim and disagreement over an exclusion are separate problems.",
      "Ask the insurer to explain which policy provision, missing document or factual concern supports its decision. If a broker arranged the policy, identify whether the broker also received premium payments, submitted the claim or gave the information now in dispute. Do not treat a broker as the insurer unless the documents show that responsibility.",
      "Create a timeline showing when the insured event occurred, when notice was given, when evidence was supplied and how the insurer responded. Preserve photographs, assessment reports, receipts and correspondence, but avoid changing documents or presenting an estimated loss as a verified amount.",
      "A requested remedy might include acknowledgement of the claim, a written explanation of coverage, review of a rejection, disclosure of the assessment basis or payment of an amount properly established under the policy. Compensation or additional loss should be supported by actual evidence and assessed under the applicable terms.",
    ],
    checklist: ["Insurer, policy type and policy reference", "Date and description of the insured event", "Premium or policy documentation where relevant", "Claim form, submission date and insurer reference", "Rejection letter, assessor report and communications", "Evidence supporting the amount or remedy requested"],
    route: "Submit a documented complaint to the insurer's official customer-care or claims department before escalating. Identify any broker, assessor or service provider only when that party had a direct role in the disputed claim decision.",
    escalation: "If an insurer does not resolve a documented complaint, organise the policy, claim reference, insurer response and supporting evidence before using the National Insurance Commission's published complaint channel. Ask for an independent review without inventing a guaranteed payout or statutory sanction.",
    example: "If a motor claim was rejected because the insurer says a document was missing, provide the claim reference, identify when the document was delivered and request a written review stating the precise policy term relied upon.",
    mistake: "Do not describe an insurer as fraudulent solely because a claim was rejected, conceal a relevant policy exclusion or circulate sensitive identity documents beyond the parties handling the case.",
    sources: [{label:"National Insurance Commission complaints portal",url:"https://complaints.naicom.gov.ng/"}],
    faqs: [{question:"Does a rejected claim automatically mean the insurer acted unlawfully?",answer:"No. The outcome depends on the policy wording, disclosed facts, evidence, insurer reasoning and the applicable complaint-review process."},{question:"What if I used an insurance broker?",answer:"Identify what the broker actually did. The broker may be relevant if it received payment, handled claim submissions or supplied disputed information, but it is not automatically the claim decision-maker."}],
  },
  {
    slug: "pension-and-retirement-benefit-complaints",
    category: "Pensions and retirement benefits",
    title: "Pension complaints: retirement benefits, unpaid contributions and records",
    description: "Organise employment records, pension statements and administrator correspondence before reporting delayed benefits or missing retirement contributions.",
    audience: "Employees, retirees or beneficiaries affected by delayed pension benefits, missing contributions, incorrect records or unresolved retirement verification.",
    context: [
      "A pension complaint may involve an employer, pension fund administrator, pension fund custodian, government pension department or the administrator of an older pension arrangement. Start by establishing which institution controls the missing record, contribution or benefit decision. Similar terminology does not mean every pension body has the same responsibility.",
      "For missing contributions, compare payslips, the retirement savings account statement, employment dates and any employer remittance information. Explain which periods appear absent and ask the responsible organisation to reconcile the records. A deduction on a payslip and a credited pension contribution should not be treated as identical without evidence.",
      "Retirement benefit delays require the date of retirement, benefit application, verification status, relevant account reference and communications from the administrator. If a beneficiary is acting on behalf of a deceased or incapacitated person, establish the authority to make the request before sharing sensitive records.",
      "Different pension schemes and public-service arrangements may have different administrators. Identify whether the matter belongs to a pension fund administrator, the National Pension Commission, the Pension Transitional Arrangement Directorate or another verified authority before choosing an escalation route.",
    ],
    checklist: ["Employer, pension administrator and relevant scheme", "Employment, retirement or benefit-application dates", "Retirement savings account or pension reference", "Payslips, pension statements and remittance records", "Administrator correspondence and complaint reference", "Evidence of authority where a beneficiary is acting"],
    route: "Address the administrator, employer or pension office that controls the record or payment being challenged. Identify the missing contribution period or disputed benefit decision and request a documented reconciliation or status update.",
    escalation: "Where the responsible administrator does not resolve the complaint, consider the authority that regulates or administers the particular pension arrangement. Include the earlier complaint, application reference, relevant employment records and the specific outstanding issue.",
    example: "A retired officer whose administrator has not processed a benefit application should state the retirement date, application reference, documents submitted, administrator response and the precise decision or information still outstanding.",
    mistake: "Do not publish your full identity number, complete pension account credentials or another beneficiary's private records. Avoid assuming that every pension delay is controlled by the same national agency.",
    sources: [{label:"National Pension Commission",url:"https://www.pencom.gov.ng/"},{label:"Pension Transitional Arrangement Directorate",url:"https://www.ptad.gov.ng/"}],
    faqs: [{question:"Who should receive a missing pension-contribution complaint?",answer:"Begin with the employer or pension administrator responsible for the missing remittance or statement and preserve the request before considering a regulator escalation."},{question:"Are all government pension complaints handled by PenCom?",answer:"Not necessarily. The appropriate route depends on the type of pension arrangement and the institution responsible for administering it."}],
  },
  {
    slug: "school-university-and-examination-complaints",
    category: "Education",
    title: "School and university complaints about fees, results and administration",
    description: "Prepare an evidence-led education complaint about admission, results, fees, transcripts, examinations or administrative treatment in Nigeria.",
    audience: "Students, parents, staff or applicants challenging an education provider's administrative decision, fee, record or examination process.",
    context: [
      "Education complaints can involve a school, university, examination body, professional programme or public education authority. Identify the actual institution that made the contested decision before copying a ministry or regulator. A delayed transcript, withheld examination result and disputed tuition payment may fall under different departments within the same institution.",
      "Describe the academic programme, application or registration reference, relevant dates and the exact decision communicated. If fees were paid, retain receipts and identify what service the payment covered. If a result was withheld, distinguish a missing administrative clearance from an allegation of examination misconduct.",
      "Where the issue concerns admission, clarify whether an offer was issued, accepted, withdrawn or still pending. Avoid claiming a guaranteed admission or statutory entitlement when the institution's criteria and the supporting documents have not been examined.",
      "The correct external authority depends on the type of educational institution. A university, polytechnic, college of education, professional school or basic-education provider may have a different regulator or supervising body. Student safety and immediate welfare concerns should also be separated from ordinary administrative disputes.",
    ],
    checklist: ["Name and category of school or academic institution", "Student, applicant, examination or transcript reference", "Dates of the disputed decision or request", "Receipts, admission documents and official correspondence", "Copies of relevant results or clearance information", "Earlier complaint or departmental response"],
    route: "Begin with the institution or examination organisation responsible for the decision. Address the registrar, complaints desk, department or published support channel appropriate to the problem and request a clear written explanation.",
    escalation: "If a properly documented institutional complaint is not resolved, identify the regulator or supervisory body relevant to the school category. Supply the earlier reference, academic records and requested remedy without sharing unrelated student information.",
    example: "A graduate waiting for a transcript should identify the institution, programme, graduation year, transcript request date, payment receipt, destination requested and prior communications before asking for release or a written explanation.",
    mistake: "Do not circulate another student's grades, full identity documents or disciplinary records. Avoid making allegations of bribery or discrimination unless you can identify the factual basis and appropriate reporting route.",
    sources: [{label:"National Universities Commission",url:"https://www.nuc.edu.ng/"},{label:"National Board for Technical Education",url:"https://www.nbte.gov.ng/"}],
    faqs: [{question:"Should every university complaint go directly to a regulator?",answer:"Generally begin with the institution that controls the academic record or administrative decision, then preserve the response before identifying an appropriate external authority."},{question:"What records help with a tuition dispute?",answer:"Keep the payment receipt, fee schedule or communication, student reference, relevant dates and the institution's explanation of the disputed charge."}],
  },
  {
    slug: "police-security-and-detention-complaints",
    category: "Security and law enforcement",
    title: "Police, security-agency and unlawful-detention complaints",
    description: "Record a security complaint carefully, prioritise urgent safety, identify the correct command or oversight authority and protect sensitive personal information.",
    audience: "People reporting police conduct, detention concerns, security-agency misconduct, extortion allegations or a failure to respond to a complaint.",
    context: [
      "A security complaint requires careful separation of an immediate emergency from a later accountability request. If someone faces present danger, a missing-person emergency or an urgent medical risk, seek immediate assistance through the appropriate emergency and legal-support channels rather than waiting for a drafted petition.",
      "For a complaint about police or security personnel, identify the agency, command, station, location and dates where those details are known. Record the conduct actually observed and distinguish the complainant's account from allegations that require independent investigation. Avoid naming an officer unless there is a reliable basis for the identification.",
      "Detention complaints should identify who is affected, the last confirmed location, the agency believed to be involved, the time of arrest or detention and whether legal or family access was requested. Do not claim that a detention is unlawful solely because the complete legal context is not yet known; explain the concern and request verification, access and a lawful review.",
      "Oversight routes may include the relevant police command, a police disciplinary authority, the National Human Rights Commission or the Public Complaints Commission, depending on the complaint. Copying unrelated agencies can increase privacy exposure without improving accountability.",
    ],
    checklist: ["Agency, station, command or incident location", "Dates and factual description of the alleged conduct", "Name or description of the affected person where appropriate", "Any arrest, complaint, case or station reference", "Available witness details or lawful supporting evidence", "Immediate safety, medical or access concerns"],
    route: "Where safe and appropriate, report the matter to the responsible security command or official complaint channel. For human-rights concerns, consider the competent rights or oversight institution and request documented investigation, lawful access or a clear status update.",
    escalation: "If the responsible authority is implicated, unresponsive or unable to provide protection, use the oversight route that matches the factual allegations and urgency. Domestic and international escalation are separate decisions; international procedures usually require a documented basis and admissibility review.",
    example: "A family seeking information about a detained relative should state the last confirmed contact, agency or station believed to be involved, date of detention, requests already made and any urgent legal or medical concern.",
    mistake: "Do not publish a vulnerable person's full identity documents, make unsupported accusations against unnamed officers or use a public petition as a substitute for urgent legal representation or emergency assistance.",
    sources: [{label:"Nigeria Police Force",url:"https://police.gov.ng/"},{label:"Police Service Commission",url:"https://psc.gov.ng/"},{label:"National Human Rights Commission",url:"https://www.nigeriarights.gov.ng/"}],
    faqs: [{question:"What should I do if someone is in immediate danger?",answer:"Use the appropriate emergency, medical or legal-assistance channel immediately. A written complaint is not an emergency-response service."},{question:"Should every security complaint be copied to multiple agencies?",answer:"No. Include only the command and oversight institutions with a genuine connection to the incident, particularly where disclosure could expose a vulnerable person."}],
  },
  {
    slug: "corruption-and-public-procurement-complaints",
    category: "Anti-corruption",
    title: "How to report suspected corruption or public-procurement irregularities",
    description: "Prepare a careful anti-corruption complaint that distinguishes evidence from suspicion, identifies the appropriate authority and protects sensitive information.",
    audience: "People reporting suspected bribery, diversion of public resources, conflict of interest, procurement irregularities or public-office misconduct.",
    context: [
      "A responsible anti-corruption complaint should explain the transaction or decision that appears questionable without treating suspicion as a proven criminal offence. Identify the organisation, programme, project or procurement process concerned and describe the specific conduct that requires investigation.",
      "Evidence may include published procurement notices, payment records, project documents, official correspondence, photographs or a traceable decision timeline. Record how information was obtained and avoid unlawfully accessing, altering or distributing confidential material. Anonymous tips and protected disclosures may require a different submission process from an ordinary signed petition.",
      "Different authorities handle different categories of misconduct. A procurement irregularity, public-officer asset or conflict issue, bribery allegation and complex financial transaction may not all belong to the same institution. Choose the body that has a real connection to the conduct instead of copying every enforcement organisation.",
      "Whistleblower safety matters. If identifying yourself could create retaliation or personal danger, consider obtaining legal advice and using an official confidential reporting channel before naming individuals or releasing documents publicly.",
    ],
    checklist: ["Institution, project, contract or public programme involved", "Dates, transaction values and decisions that can be verified", "Published procurement or budget records where relevant", "Specific documents or witnesses supporting the concern", "Any previous internal report or official response", "A safe contact method and necessary confidentiality request"],
    route: "Select the official reporting channel that matches the alleged conduct, such as a competent anti-corruption authority, procurement oversight body or public-service complaints institution. State clearly that the facts are presented for investigation rather than as an established finding of guilt.",
    escalation: "If an initial report receives no response or the matter concerns a distinct regulator, preserve the original submission reference and identify what remains unresolved. Significant public-interest, cross-border or rights implications may require specialist legal advice before further escalation.",
    example: "A resident reporting a public project that appears incomplete despite a documented payment should identify the project location, responsible agency, published project information, observed condition and the precise records an investigator should verify.",
    mistake: "Do not fabricate contract values, circulate forged documents, label a person guilty before investigation or reveal protected personal information merely to make an allegation appear stronger.",
    sources: [{label:"Economic and Financial Crimes Commission",url:"https://efcc.gov.ng/"},{label:"Independent Corrupt Practices Commission",url:"https://icpc.gov.ng/"},{label:"Code of Conduct Bureau",url:"https://ccb.gov.ng/"}],
    faqs: [{question:"Can I report suspicious conduct without proving a criminal offence?",answer:"Yes. Explain the observable facts, identify supporting records and ask the competent authority to investigate, while making clear which points remain allegations."},{question:"Should I include every anti-corruption agency?",answer:"No. Use the authority that matches the actual conduct, relevant jurisdiction and official reporting channel."}],
  },
  {
    slug: "tenancy-landlord-and-civil-disputes",
    category: "Civil disputes",
    title: "Landlord, tenancy and other private civil-dispute complaints",
    description: "Organise a private tenancy or civil dispute, choose mediation or the correct local filing channel and avoid unsupported claims about rent, eviction or legal deadlines.",
    audience: "Tenants, landlords, consumers or private parties dealing with a contract, property, rent, repair, deposit or other civil disagreement.",
    context: [
      "A private civil dispute is not automatically a criminal case or a matter for every public complaints institution. Identify the parties, agreement, property location and the precise disagreement. A tenancy dispute may involve a landlord, property manager, tenant or agent, while a separate commercial disagreement may require negotiation, mediation or court guidance.",
      "For rent or repair problems, preserve the tenancy agreement, payment receipts, communications, photographs and any notice received. A large rent increase is not, by itself, proof that the increase is unlawful; the relevant agreement, local jurisdiction and applicable legal process must be examined.",
      "An eviction or access dispute should be described factually. Explain what notice was delivered, who took the action and whether access or services were affected, but do not label an incident constructive eviction unless the evidence supports that conclusion. Where personal safety is threatened, seek appropriate emergency or legal assistance.",
      "Mediation can be appropriate when both sides are willing to participate and the dispute is within the mediator's remit. If mediation fails, the correct court or registry depends on the property location, value, claim type and applicable procedure.",
    ],
    checklist: ["Names and roles of the private parties", "Property address or location of the underlying dispute", "Agreement, rent receipts, invoices or payment records", "Notices and dated communications", "Photographs or repair records where relevant", "Any prior mediation, negotiation or court reference"],
    route: "Address the individual or organisation actually involved in the dispute and consider a verified mediation service where appropriate. Choose the state or Federal Capital Territory route that corresponds to the property or transaction location.",
    escalation: "If reasonable discussion or mediation does not resolve the issue, seek advice about the competent court, filing registry or recognised alternative-dispute-resolution institution. Do not confuse a disciplinary complaint, police report and private civil claim when they address different issues.",
    example: "A tenant disputing a withheld security deposit should identify the tenancy period, amount paid, property condition, move-out date, landlord's explanation and the requested reconciliation or refund.",
    mistake: "Do not invent a statutory notice period, assert that any percentage rent increase is illegal, name an unknown landlord or use criminal accusations to pressure a private party in an ordinary contract disagreement.",
    sources: [{label:"Abuja Multi-Door Court",url:"https://www.fcthighcourt.gov.ng/abuja-multi-door-court-amdc/"},{label:"Lagos Citizens' Mediation Centre",url:"https://lagosstatemoj.org/cmc/"}],
    faqs: [{question:"Does a high rent increase automatically make a landlord's action unlawful?",answer:"No. The answer depends on the tenancy agreement, location, applicable law and the process actually followed."},{question:"Can I send a private rent dispute to any federal authority?",answer:"Usually not. Identify the appropriate local mediation, tenancy or court route and address the actual landlord or property manager involved."}],
  },
  {
    slug: "land-planning-and-building-control-complaints",
    category: "Urban planning and development control",
    title: "Land-use, planning-permission and building-control complaints",
    description: "Identify the responsible development-control authority and organise evidence about planning approval, construction, land use or demolition concerns.",
    audience: "Residents, property owners or applicants affected by a planning decision, unauthorised construction, land-use conflict or development-control action.",
    context: [
      "Planning and development-control responsibilities depend heavily on location. An Abuja construction complaint is not necessarily handled by the same authority as a Lagos building-control dispute or a planning matter in another state. Begin with the property address and the agency that issued, withheld or enforced the relevant decision.",
      "Identify the specific concern: planning approval, building-setback compliance, structural safety, a demolition notice, noise or obstruction arising from construction, a disputed occupancy decision or a land-use change. These issues require different records and should not be merged into a general allegation that a property is illegal.",
      "Preserve application references, official notices, approved drawings where lawfully available, photographs taken safely and communications with the responsible office. If a building appears immediately unsafe, prioritise the relevant emergency and public-safety process rather than waiting for an ordinary administrative complaint.",
      "Property ownership, planning permission and civil possession are related but distinct. A planning authority may investigate compliance while a court, mediator or land registry deals with a separate title or private ownership question.",
    ],
    checklist: ["Exact property address, state and local development area", "Responsible planning or building-control institution", "Application, permit, notice or reference number", "Relevant photographs and dates of the activity", "Copies of official correspondence or enforcement notices", "Clear explanation of the safety or administrative concern"],
    route: "Contact the planning, development-control or building-safety office responsible for the property's location. Identify whether you seek an inspection, clarification of approval status, review of an enforcement decision or a documented response to a public-safety concern.",
    escalation: "If the relevant office does not respond, preserve the original application or complaint reference and identify the supervising administrative or complaint authority. Seek legal advice where a demolition, ownership dispute or court order requires urgent or specialist action.",
    example: "A resident reporting a suspected unsafe building in Abuja should state the location, visible condition, dates observed, any prior report and the requested official inspection without claiming to know the builder's permit status.",
    mistake: "Do not publish unverified ownership claims, assume all construction without a visible sign lacks approval or send an FCT planning dispute to a Lagos building authority.",
    sources: [{label:"FCT Department of Development Control",url:"https://dodc.fcta.gov.ng/"},{label:"Lagos State Building Control Agency",url:"https://lasbca.lagosstate.gov.ng/"}],
    faqs: [{question:"Why does the property location matter?",answer:"Planning and building-control jurisdiction is linked to the state, Federal Capital Territory or other local authority responsible for the specific site."},{question:"Is a planning complaint the same as a land-ownership claim?",answer:"No. Planning compliance, title disputes and private possession may require different institutions and procedures."}],
  },
  {
    slug: "public-service-and-administrative-complaints",
    category: "General administrative complaints",
    title: "Complaints about public-service delays and administrative unfairness",
    description: "Prepare a focused complaint about an unexplained administrative delay, refused service, missing decision or other public-service problem in Nigeria.",
    audience: "People affected by an unexplained delay, missing public record, refusal to process an application or other administrative service problem.",
    context: [
      "An administrative complaint should identify the public institution, office, application or service involved. State what was requested, when the request was made, what documents were provided and how the institution responded. A clear timeline is usually more persuasive than a general accusation that an entire agency is corrupt or inefficient.",
      "Differentiate a delay from a formal refusal, an incomplete application, a missing payment or a dispute over an eligibility decision. Each situation requires a different remedy. If the office has asked for a document, explain whether it was supplied and provide the relevant reference.",
      "Where a public-service decision affects employment, benefits, identity documents, licensing or access to records, preserve the notice and identify the unit responsible. Do not assume that an unrelated regulator or criminal-enforcement body can direct the agency to issue the outcome you prefer.",
      "Complaint institutions and service-delivery oversight bodies can be relevant when the responsible office does not provide a clear answer. Their usefulness depends on being able to identify the original application, the responsible institution and the practical administrative remedy requested.",
    ],
    checklist: ["Public institution, department and office location", "Application, case or service reference", "Submission date and documents provided", "Copies of receipts, acknowledgement and official responses", "The practical effect of the delay or disputed decision", "A clear request for action, explanation or review"],
    route: "Start with the office that controls the public-service decision and use an official complaints or enquiries channel. Request an acknowledgement or reference and identify whether you want a status update, a reasoned decision, correction of a record or review of an administrative action.",
    escalation: "If the responsible institution does not address the issue, a relevant public complaints or service-delivery authority may be appropriate. Include the original application, correspondence and outstanding question rather than copying unrelated agencies.",
    example: "If an application remains unanswered after repeated visits, provide the application reference, submission date, office contacted, documents supplied and the specific request for a written decision or status update.",
    mistake: "Do not demand that an oversight body override an independent court, issue a document outside its mandate or treat an incomplete application as evidence of intentional misconduct without supporting facts.",
    sources: [{label:"Public Complaints Commission",url:"https://pcc.gov.ng/"},{label:"SERVICOM",url:"https://servicom.gov.ng/"}],
    faqs: [{question:"What makes a public-service complaint actionable?",answer:"Identify the responsible office, application reference, dated events, prior correspondence and the specific administrative response you are requesting."},{question:"Should every delayed application be reported as corruption?",answer:"No. Describe the delay and any verifiable irregularity separately. An allegation of corruption needs a factual basis and the correct reporting channel."}],
  },
  {
    slug: "judicial-conduct-and-court-service-complaints",
    category: "Judiciary and justice administration",
    title: "Judicial conduct, court-registry and justice-administration complaints",
    description: "Distinguish a court appeal from a judicial-conduct complaint, identify the relevant court or oversight authority and protect confidential case material.",
    audience: "Court users and litigants concerned about registry service, delayed administrative action, judicial conduct or access to case information.",
    context: [
      "A disagreement with a court judgment is different from a complaint about judicial conduct or court administration. A petition cannot replace an appeal, reopen a final decision on its merits or instruct an oversight body to decide an active case. Where a legal deadline or appeal is involved, obtain appropriate legal advice promptly.",
      "For a court-registry issue, identify the court, case reference, filing date, registry action requested and the response received. Missing certified records, unexplained file-handling delays and administrative service problems should be described without assuming that the judge personally caused them.",
      "A judicial-conduct complaint requires a specific, evidence-based account of the behaviour being questioned and the competent disciplinary channel. Avoid unsupported claims of bias, bribery or misconduct. Consider whether public disclosure could prejudice active proceedings or breach confidentiality.",
      "The proper route depends on whether the matter concerns a court's administrative office, a state or federal judicial institution, a professional practitioner or an actual challenge to a judgment. These channels must not be collapsed into a single generic complaint.",
    ],
    checklist: ["Name and level of the court or justice institution", "Case number and relevant filing dates", "The specific administrative action or conduct in issue", "Registry correspondence and available official receipts", "Any earlier request or written complaint", "A requested remedy that does not replace an appeal"],
    route: "Direct an administrative complaint to the relevant court registry or supervising office, while a properly supported conduct complaint should follow the published judicial-disciplinary process. Use professional legal advice where the issue is an appeal or urgent court application.",
    escalation: "If a documented administrative or conduct complaint remains unresolved, identify the institution with authority over the court or judicial officer involved. Preserve confidentiality and avoid submitting a petition as though it were an appeal against a judicial decision.",
    example: "A litigant waiting for a certified court record should identify the court, suit number, application date, payment receipt, registry requests and the precise document still outstanding.",
    mistake: "Do not send a judgment appeal to a conduct body, invent a court email address, publish confidential pleadings unnecessarily or ask an administrator to interfere with a pending judicial decision.",
    sources: [{label:"National Judicial Council",url:"https://njc.gov.ng/"},{label:"National Human Rights Commission",url:"https://www.nigeriarights.gov.ng/"}],
    faqs: [{question:"Can a petition replace an appeal against a court judgment?",answer:"No. An appeal is a separate legal procedure with its own filing requirements and deadlines, and a disciplinary petition cannot substitute for it."},{question:"Where should a court-registry delay be reported?",answer:"Start with the relevant court registry or supervising administrative office and identify the case reference, requested document and earlier correspondence."}],
  },
  {
    slug: "diaspora-embassy-and-consular-complaints",
    category: "Diaspora and consular matters",
    title: "Diaspora, embassy, passport and consular-service complaints",
    description: "Find the right Nigerian embassy or consulate, document a passport or welfare concern and distinguish consular support from an immediate overseas emergency.",
    audience: "Nigerians abroad and their families dealing with passport applications, consular appointments, welfare concerns or contact with a Nigerian diplomatic mission.",
    context: [
      "A consular complaint should identify the country, city and Nigerian embassy, high commission or consulate responsible for the location. Diplomatic missions serve defined jurisdictions, so a complaint sent to a mission in another country may be delayed or ignored even when the underlying issue is genuine.",
      "Passport and appointment complaints should include the application reference, payment date, booking information, mission contacted and the current status communicated. Distinguish a technical payment issue from a missing appointment, incomplete application, document collection problem or emergency travel-document request.",
      "For welfare issues abroad, state the affected person's location, contact status, relevant employer or institution and the assistance being requested. Do not assume that a Nigerian mission can override the host country's immigration, policing or court system.",
      "Where someone is at immediate risk, contact the host-country emergency service or an appropriate local support organisation first. Consular communication can then help establish contact, welfare support and the official steps available in the particular country.",
    ],
    checklist: ["Host country, city and responsible Nigerian mission", "Passport, appointment, application or case reference", "Dates of payment, appointment or welfare incident", "Mission correspondence and previously contacted officials", "Safe contact details for the affected person", "Evidence of any urgent medical or protection concern"],
    route: "Use the official diplomatic-mission directory to identify the embassy, high commission or consulate responsible for the relevant country. Address passport or consular complaints to that mission or the appropriate Nigerian immigration or foreign-affairs channel.",
    escalation: "If a mission does not address a documented consular or welfare request, consider the competent foreign-affairs, immigration or diaspora-support authority. Include the host-country location and previous mission reference, and use emergency services immediately where safety is threatened.",
    example: "A Nigerian waiting for a passport appointment abroad should identify the country, mission, application ID, payment confirmation, appointment date and each attempt to obtain an update before requesting an official status response.",
    mistake: "Do not circulate a passport biodata page publicly, send a country-specific matter to an unrelated embassy or treat an active overseas emergency as a routine support ticket.",
    sources: [{label:"Nigerian diplomatic missions",url:"https://foreignaffairs.gov.ng/diplomatic-missions/"},{label:"Nigerians in Diaspora Commission",url:"https://nidcom.gov.ng/"}],
    faqs: [{question:"Which Nigerian embassy should receive my complaint?",answer:"Use the official diplomatic-mission directory and select the mission responsible for the country or consular jurisdiction where the issue occurred."},{question:"What if someone abroad is in immediate danger?",answer:"Contact the relevant host-country emergency services immediately, then seek consular support from the responsible Nigerian mission."}],
  },
  {
    slug: "international-human-rights-escalation",
    category: "International escalation and human-rights advocacy",
    title: "When an international human-rights escalation is appropriate",
    description: "Assess whether a complaint has an international human-rights basis, document domestic remedies and distinguish advocacy from a formal international legal filing.",
    audience: "Individuals or organisations considering international advocacy over serious, documented human-rights concerns or systemic failures of protection.",
    context: [
      "An international escalation is not an automatic next step for every unresolved local complaint. A private billing disagreement, routine administrative delay or isolated consumer dispute does not become an international human-rights case merely because an overseas institution is mentioned. Identify the serious rights issue, affected people, responsible authorities and documented domestic response.",
      "Different international bodies serve different functions. A United Nations procedure, African regional mechanism, ECOWAS court process, parliamentary advocacy contact or diplomatic mission may have distinct jurisdiction, admissibility requirements and submission channels. An advocacy email is not the same as commencing a formal court or treaty-body case.",
      "Document domestic complaints carefully. Record which Nigerian institutions were contacted, complaint dates, responses, any obstacles to protection and why an international approach may be necessary. Where ordinary remedies remain available, explain their status rather than pretending they have been exhausted.",
      "Safety and consent are essential. A public campaign or submission may expose complainants, witnesses or vulnerable communities. Use lawful evidence, obtain permission where needed and avoid naming an international institution unless the facts genuinely connect to its published mandate.",
    ],
    checklist: ["A clear description of the serious rights concern", "Identity or category of affected people with privacy protected", "Dates, locations and independently supportable facts", "Domestic complaints, responses and remaining remedies", "Reasons the proposed international body may have jurisdiction", "Consent, security considerations and the specific action requested"],
    route: "Choose a verified official international or regional procedure that matches the issue. Distinguish a United Nations special-procedure submission, a regional human-rights complaint, a parliamentary advocacy request and a formal court filing; do not invent email addresses or use mass copied recipients.",
    escalation: "Formal international mechanisms may require eligibility, admissibility, standing, domestic-remedy or procedural assessments. Seek qualified legal advice where a case involves litigation, urgent protective measures or substantial personal risk, and describe advocacy requests honestly as advocacy.",
    example: "A documented pattern of threats against a community may justify international advocacy where domestic authorities were informed, the response failed to address the risk and the selected international mechanism has a relevant human-rights mandate.",
    mistake: "Do not present a routine loan refund as a United Nations case, claim that sending an email creates a court proceeding, copy every foreign parliament or invent official international contact details.",
    sources: [{label:"UN Human Rights Office",url:"https://www.ohchr.org/"},{label:"ECOWAS Court of Justice",url:"https://www.courtecowas.org/"},{label:"National Human Rights Commission",url:"https://www.nigeriarights.gov.ng/"}],
    faqs: [{question:"Can every unresolved Nigerian complaint be sent to the United Nations?",answer:"No. A relevant international mechanism requires a genuine connection between the facts, the rights issue, the body's mandate and any applicable procedural conditions."},{question:"Is a parliamentary advocacy email the same as filing an international case?",answer:"No. Advocacy correspondence can request attention or support, while a court or treaty-body proceeding has separate procedural and jurisdictional requirements."}],
  },
  {
    slug: "evidence-checklist-and-personal-data-safety",
    category: "Evidence and privacy",
    title: "Complaint evidence checklist and personal-data safety",
    description: "Choose useful supporting records, protect personal data, preserve complaint references and avoid disclosing passwords, identity numbers or confidential documents.",
    audience: "Anyone preparing evidence for a consumer, workplace, public-service, financial, security or human-rights complaint.",
    context: [
      "Good evidence makes a complaint easier to assess, but more attachments do not always produce a stronger case. Select documents that connect directly to the issue, identify what each record proves and remove information that the recipient does not need. A clear timeline supported by three relevant documents can be more useful than dozens of unrelated screenshots.",
      "Common evidence includes application acknowledgements, transaction receipts, account statements, support tickets, official correspondence, contracts, photographs and written decisions. Distinguish an original document from a summary or inference and preserve the date on which it was created or received.",
      "Financial and identity information should be shared carefully. Never include passwords, payment PINs, one-time codes, security answers or complete card details in a petition. Mask account or identity numbers where the full value is not necessary, and use a trusted verified channel if a responsible institution legitimately requests additional information.",
      "Complaints involving medical treatment, children, employment records, detention or vulnerable witnesses require additional care. Explain the relevant facts without publishing an unrelated diagnosis, another person's private correspondence or confidential evidence that you are not authorised to disclose.",
    ],
    checklist: ["A dated summary of the relevant events", "The original decision, transaction or application reference", "Records identifying the responsible institution", "Proof of prior contact and any complaint reference", "Only the documents needed to support the requested remedy", "Redaction of passwords, PINs, full identity numbers and unrelated data"],
    route: "Send evidence only through an official verified email address, secure complaint portal, recognised physical registry or another legitimate channel. Check that the recipient is authorised to handle the issue and keep a record of what was submitted.",
    escalation: "When escalating, provide the earlier complaint, response, unresolved issue and the minimum additional evidence necessary for the oversight body to understand the case. Do not assume that a regulator or public agency should receive every private document collected during the original dispute.",
    example: "For a disputed loan deduction, provide a redacted account statement, repayment schedule, mandate reference and the lender's correspondence. The statement proves the transaction history; it does not make the account-holding bank the responsible lender.",
    mistake: "Do not alter screenshots, guess missing dates, share another person's confidential records or send identity documents to an unverified email address merely because it appears in a search result.",
    sources: [{label:"Nigeria Data Protection Commission",url:"https://ndpc.gov.ng/"},{label:"National Human Rights Commission",url:"https://www.nigeriarights.gov.ng/"}],
    faqs: [{question:"Should I include my full account number in a complaint?",answer:"Include only what the verified recipient genuinely needs. A masked account number and transaction reference are often enough for an initial explanation."},{question:"Can I use screenshots as evidence?",answer:"Yes, where relevant and lawfully obtained. Preserve their original context, avoid alterations and redact unrelated personal information."}],
  },
];

if (EDITORIAL_GUIDES.length !== 18) {
  throw new Error(`Expected 18 independently useful complaint guides, received ${EDITORIAL_GUIDES.length}.`);
}
